### ISSUE TITLE
waybar configs are missing 

### ISSUE THREAD

**Issue by ALEX5402** [Abaan404/dotfiles#4]
oops i thought that is waybar

**Comment by Mohamed-Gibreel** [comment]
Hey @ALEX5402 I'm a bit confused, I'm also unable to find waybar configs. What bar is he using if it isn't waybar ?

Apologies if my question is bit dumb, I am new to arch/hyprland & ricing linux.

**Comment by Abaan404** [comment]
I'm using ags (https://github.com/Aylur/ags) instead of waybar

[heres](https://github.com/Abaan404/dotfiles/blob/d9cd66055afa17a66cff42e3906eb987cb719ade/config/ags/ts/windows/bar.ts) where my bar is in my dots
